# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SCDL
baseurl: "/dynasty"
url: "http://moyden.com" # the base hostname & protocol for your site
collections:
  teams:
    output: true
    permalink: /teams/:path/

defaults:
  - scope:
      path: ""
      type: teams
    values:
      layout: teampage

# Build settings
markdown: kramdown

exclude: [node_modules, gulpfile.js, package.json]
